#!/bin/sh

BASE_DIR=$(readlink -f $(dirname $0))
mkdir -p /tmp/build-buck
(
    cd /tmp/build-buck
    wget https://github.com/facebook/buck/archive/refs/tags/v2021.01.12.01.tar.gz
    tar xf v2021.01.12.01.tar.gz
    cd buck-2021.01.12.01
    # The bundled version of buck doesn't play nicely when python2 is not installed, so fix that
    sed -i 's/python2.7 python2 python/python3 python2.7 python2 python/g' ./bin/buck
    ant
    ./bin/buck build --config java.target_level=11 --config java.source_level=11 --show-output buck
    cp buck-out/gen/ce9b6f2e/programs/buck.pex $BASE_DIR/buck-v2021.02.12.01.pex
)