java_library(
    name = 'main',
    srcs = glob(['src/main/java/**/*.java']),
    resources = glob(['src/main/resources/**']),
    deps = [
        '//annotations/time:annotations-time',
        '//utils/clock:clock',
    ],
    provided_deps = ['//:checker-framework'],
    annotation_processor_deps = ['//:checker-framework'],
    annotation_processors = ['org.checkerframework.checker.units.UnitsChecker'],
    visibility = ['PUBLIC'],
)