java_library(
    name = "clock",
    srcs = glob(["src/main/java/**/*.java"]),
    resources = glob(["src/main/resources/**"]),
    deps = ["//annotations/time:annotations-time"],
    plugins = ["//:checker-plugin"],
    visibility = ["//visibility:public"],
)