java_library(
    name = 'annotations-time',
    srcs = glob(['src/main/java/**/*.java']),
    resources = glob(['src/main/resources/**']),
    deps = ['//:checker-qual'],
    visibility = ['PUBLIC'],
)